sources:
  - name: staging  #By default, schema will be the same as name. Add schema only if you want to use a source name that differs from the existing schema
    database: airbnb  
    schema: staging  
    tables:
      - name: src_bookings
      - name: src_hosts
      - name: src_listings